name: ProposalAction

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 매일 09:00 KST
    - cron: "0 3 * * *" # 매일 12:00 KST
    - cron: "0 6 * * *" # 매일 15:00 KST
    - cron: "0 9 * * *" # 매일 18:00 KST
    - cron: "0 12 * * *" # 매일 21:00 KST
    - cron: "0 15 * * *" # 매일 00:00 KST (다음 날)
    - cron: "0 18 * * *" # 매일 03:00 KST (다음 날)
    - cron: "0 21 * * *" # 매일 06:00 KST (다음 날)

jobs:
  cronjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: |
          cd scheduling
          cat package.json
          npm install

      - name: Run webhook JS
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          WEBHOOK_ENDPOINT: ${{ secrets.WEBHOOK_ENDPOINT }}
        run: cd scheduling && node --experimental-strip-types ./src/index.ts
